# Generated by Django 5.0.2 on 2024-02-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhPho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanhpho', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinh', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanhuyen', models.CharField(max_length=255)),
                ('thanhpho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thanhpho')),
            ],
        ),
        migrations.AddField(
            model_name='thanhpho',
            name='tinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tinh'),
        ),
    ]
